"use client";

import { useEffect, useMemo, useState } from "react";
import { frappeApi } from "@/lib/api";
import { Button } from "@/components/common/Button";

type Account = { name: string; account_name: string; is_group?: number; disabled?: number };

export function ManagerExpenseManagement({ onCreated }: { onCreated: () => void }) {
  const [expenses, setExpenses] = useState<Account[]>([]);
  const [payments, setPayments] = useState<Account[]>([]);
  const [form, setForm] = useState({ amount: "", expense_date: new Date().toISOString().slice(0, 10), expense_account: "", paid_from_account: "", description: "", reference: "" });
  const [category, setCategory] = useState({ account_name: "", parent_account: "" });
  const [message, setMessage] = useState("");
  async function load() { const { data } = await frappeApi.managerExpenseAccounts(); setExpenses(data.expense_accounts || []); setPayments(data.payment_accounts || []); }
  useEffect(() => { load().catch(() => setMessage("Unable to load expense accounts.")); }, []);
  const leaves = useMemo(() => expenses.filter((a) => !a.is_group && !a.disabled), [expenses]);
  const parents = useMemo(() => expenses.filter((a) => a.is_group && !a.disabled), [expenses]);
  async function submitExpense(e: React.FormEvent) { e.preventDefault(); setMessage(""); try { const { data } = await frappeApi.managerCreateExpense({ ...form, amount: Number(form.amount) }); setMessage(`Expense posted in ${data.journal_entry}.`); setForm((v) => ({ ...v, amount: "", description: "", reference: "" })); onCreated(); } catch { setMessage("Unable to post this expense. Check the accounts and amount."); } }
  async function addCategory(e: React.FormEvent) { e.preventDefault(); setMessage(""); try { await frappeApi.managerCreateExpenseAccount(category.account_name, category.parent_account); setCategory({ account_name: "", parent_account: "" }); await load(); setMessage("Expense category created."); } catch { setMessage("Unable to create this expense category."); } }
  return <section className="grid gap-6 lg:grid-cols-2"><form onSubmit={submitExpense} className="space-y-3 rounded-lg border bg-white p-5"><h2 className="font-semibold">Add expense</h2><div className="grid gap-3 sm:grid-cols-2"><input required type="number" min="0.01" step="0.01" placeholder="Amount" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} className="rounded border p-2" /><input required type="date" value={form.expense_date} onChange={(e) => setForm({ ...form, expense_date: e.target.value })} className="rounded border p-2" /><select required value={form.expense_account} onChange={(e) => setForm({ ...form, expense_account: e.target.value })} className="rounded border p-2"><option value="">Expense category</option>{leaves.map((a) => <option key={a.name} value={a.name}>{a.account_name}</option>)}</select><select required value={form.paid_from_account} onChange={(e) => setForm({ ...form, paid_from_account: e.target.value })} className="rounded border p-2"><option value="">Paid from account</option>{payments.map((a) => <option key={a.name} value={a.name}>{a.account_name}</option>)}</select></div><input placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="w-full rounded border p-2" /><input placeholder="Reference (optional)" value={form.reference} onChange={(e) => setForm({ ...form, reference: e.target.value })} className="w-full rounded border p-2" /><Button type="submit">Post expense</Button>{message && <p className="text-sm text-slate-600">{message}</p>}</form><form onSubmit={addCategory} className="space-y-3 rounded-lg border bg-white p-5"><h2 className="font-semibold">Expense categories</h2><input required placeholder="New category name" value={category.account_name} onChange={(e) => setCategory({ ...category, account_name: e.target.value })} className="w-full rounded border p-2" /><select required value={category.parent_account} onChange={(e) => setCategory({ ...category, parent_account: e.target.value })} className="w-full rounded border p-2"><option value="">Parent expense group</option>{parents.map((a) => <option key={a.name} value={a.name}>{a.account_name}</option>)}</select><Button type="submit">Add category</Button><div className="max-h-48 overflow-y-auto border-t pt-3">{leaves.map((a) => <div key={a.name} className="flex items-center justify-between py-2 text-sm"><span>{a.account_name}</span><button type="button" className="text-red-700" onClick={async () => { await frappeApi.managerSetExpenseAccountEnabled(a.name, false); await load(); }}>Disable</button></div>)}</div></form></section>;
}
